### ISSUE TITLE
fs-fuse subfs

### ISSUE THREAD

**Issue by fixerivan** [piranna/fs-fuse#6]
hi, trying to use https://github.com/juliangruber/subfs to generate fs-like object to pass to FsFuse

edited your server.js

added 

const subfs = require('subfs')
const sub = subfs('/tmp/', fs);

and changed FsFuse parameter: 

fuse.mount(path, FsFuse(sub), function(error)

mounting it with: node server.js null test

when i tried to list the contest of the dir i am getting 

ls: cannot access 'test': Function not implemented

what am i doing wrong? thx

**Comment by piranna** [comment]
> when i tried to list the contest of the dir i am getting
> 
> ls: cannot access 'test': Function not implemented

Can you give me the full stack? Or is the error in the shell? Can you add traces in the code?

**Comment by fixerivan** [comment]
had to check your commit history - the problem was in:

const sub = subfs('/tmp/', fs);

you changed the order of parameters - if I do const sub = subfs(fs, '/tmp/'); everything works as expected
